services:
  api:
    image: api-legado-dev:latest
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env.prod
    restart: unless-stopped
    volumes:
      - whatsapp_session:/usr/src/app/whatsapp-session

volumes:
  whatsapp_session:
