export enum AuditActionEnum {
  SUBMISSION_APPROVED = 'SUBMISSION_APPROVED',
  SUBMISSION_REJECTED = 'SUBMISSION_REJECTED',
  EVENT_APPROVED = 'EVENT_APPROVED',
  EVENT_REJECTED = 'EVENT_REJECTED',
  EVENT_CANCELLED = 'EVENT_CANCELLED',
  CONTRIBUTION_REPORT_REVIEWED = 'CONTRIBUTION_REPORT_REVIEWED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  USER_BANNED = 'USER_BANNED',
  USER_UNBANNED = 'USER_UNBANNED',
  XP_MANUAL_ADJUSTMENT = 'XP_MANUAL_ADJUSTMENT',
}
