export enum TransactionCategoryEnum {
  XP_REWARD = 'XP_REWARD',
  TOKEN_REWARD = 'TOKEN_REWARD',
  STORE_PURCHASE = 'STORE_PURCHASE',
  MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT',
  AUDITOR_REWARD = 'AUDITOR_REWARD',
  TOKEN_TRANSFER = 'TOKEN_TRANSFER',
  PENALTY = 'PENALTY',
}
