export enum TrackItemType {
  RESOURCE = 'RESOURCE',
  TEXT = 'TEXT',
  PROOF = 'PROOF',
  COURSE_COMPLETION = 'COURSE_COMPLETION',
  EVENT = 'EVENT',
  MISSION = 'MISSION',
  CHECKPOINT = 'CHECKPOINT',
}
