export enum NotificationType {
  SUBMISSION_APPROVED = 'SUBMISSION_APPROVED',
  MISSION_WON = 'MISSION_WON',
  SUBMISSION_REJECTED = 'SUBMISSION_REJECTED',
  CONTRIBUTION_REPORT_UPHELD = 'CONTRIBUTION_REPORT_UPHELD',
  CONTRIBUTION_REPORT_RECEIVED = 'CONTRIBUTION_REPORT_RECEIVED',
}
