export enum NotificationType {
  SUBMISSION_APPROVED = 'SUBMISSION_APPROVED',
  MISSION_WON = 'MISSION_WON',
  SUBMISSION_REJECTED = 'SUBMISSION_REJECTED',
  CONTRIBUTION_REPORT_UPHELD = 'CONTRIBUTION_REPORT_UPHELD',
  CONTRIBUTION_REPORT_RECEIVED = 'CONTRIBUTION_REPORT_RECEIVED',
  TRACK_MILESTONE_APPROVED = 'TRACK_MILESTONE_APPROVED',
  TRACK_BADGE_GRANTED = 'TRACK_BADGE_GRANTED',
  LEGAL_DOCUMENT_UPDATED = 'LEGAL_DOCUMENT_UPDATED',
  EVENT_UPDATED = 'EVENT_UPDATED',
  EVENT_CANCELLED = 'EVENT_CANCELLED',
}
